package com.bits.saas.util.query;

public final class DBQueries {
	
	public static final String ENTERPRISE_INSERT = "INSERT INTO SPENTERPRISE (ENTERPRISE_ID,NAME) VALUES (SPENTERPRISE_S.NEXTVAL,?)";
	
	public static final String ENTERPRISE_SELECT_BYID = "SELECT ENTERPRISE_ID, NAME FROM SPENTERPRISE WHERE ENTERPRISE_ID=?";
	
	public static final String ENTERPRISE_UPDATE_BYID = "UPDATE SPENTERPRISE SET NAME = ?, ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE ENTERPRISE_ID=?";
	
	public static final String ENTERPRISE_DELETE_BYID = "DELETE FROM SPENTERPRISE WHERE ENTERPRISE_ID = ?";
	
	public static final String ENTERPRISE_SELECT_ALL = "SELECT ENTERPRISE_ID, NAME FROM SPENTERPRISE ORDER BY ENTERPRISE_ID";
	
	public static final String PRODUCT_INSERT = "INSERT INTO SPPRODUCT (PRODUCT_ID,NAME,ENTERPRISE_ID) VALUES (?,?,?)";
	
	public static final String PRODUCT_SELECT_BYID = "SELECT P.PRODUCT_ID,P.NAME,P.REVENUE,P.REPUTATION,P.ENTERPRISE_ID,E.NAME FROM SPPRODUCT P INNER JOIN SPENTERPRISE E ON P.ENTERPRISE_ID = E.ENTERPRISE_ID WHERE P.PRODUCT_ID=?";
	
	public static final String PRODUCT_UPDATE_BYID = "UPDATE SPPRODUCT SET NAME=?,ENTERPRISE_ID=?,ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE PRODUCT_ID=?";
	
	public static final String PRODUCT_SELECT_BYENTID = "SELECT P.PRODUCT_ID,P.NAME,P.REVENUE,P.ENTERPRISE_ID,E.NAME FROM SPPRODUCT P INNER JOIN SPENTERPRISE E ON P.ENTERPRISE_ID = E.ENTERPRISE_ID WHERE P.ENTERPRISE_ID=?";
	
	public static final String PRODUCT_DELETE_BYID = "DELETE FROM SPPRODUCT WHERE PRODUCT_ID = ?";
	
	public static final String PRODUCT_GET_SEQ = "SELECT SPPRODUCT_S.NEXTVAL FROM DUAL";
	
	public static final String PRODUCT_DETAIL_INSERT = "INSERT INTO SPPRODUCTDETAIL (PRODUCTDETAIL_ID,PRODUCT_ID,BLOCK1,BLOCK2,BLOCK3) VALUES (SPPRODUCTDETAIL_S.NEXTVAL,?,?,?,?)";
	
	public static final String PRODUCTDETAIL_DELETE_BYPRODID = "DELETE FROM SPPRODUCTDETAIL WHERE PRODUCT_ID = ?";
	
	public static final String PRODUCTDETAIL_SELECT_BYPRODID = "SELECT PRODDET.PRODUCT_ID,PROD.NAME,PRODDET.BLOCK1,PRODDET.BLOCK2,PRODDET.BLOCK3 FROM SPPRODUCTDETAIL PRODDET INNER JOIN SPPRODUCT PROD ON PROD.PRODUCT_ID = PRODDET.PRODUCT_ID WHERE PRODDET.PRODUCT_ID=?";
	
	public static final String PRODUCTDETAIL_UPDATE_BYPRODID = "UPDATE SPPRODUCTDETAIL SET BLOCK1=?,BLOCK2=?,BLOCK3=? WHERE PRODUCT_ID=?";
	
	public static final String CUSTOMER_INSERT = "INSERT INTO SPCUSTOMER(CUSTOMER_ID,NAME,PRODUCT_ID,EMAIL,REPUTATION,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (SPCUSTOMER_S.NEXTVAL,?,?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String CUSTOMER_SELECT_BYID = "SELECT CUST.CUSTOMER_ID,CUST.NAME,CUST.EMAIL,CUST.REPUTATION,CUST.REVENUE,PROD.PRODUCT_ID,PROD.NAME FROM SPCUSTOMER CUST INNER JOIN SPPRODUCT PROD ON CUST.PRODUCT_ID = PROD.PRODUCT_ID WHERE CUST.CUSTOMER_ID=?";
	
	public static final String CUSTOMER_SELECT_BYPRODUCTID = "SELECT CUST.CUSTOMER_ID,CUST.NAME,CUST.EMAIL,CUST.REPUTATION,CUST.REVENUE,PROD.NAME FROM SPCUSTOMER CUST INNER JOIN SPPRODUCT PROD ON CUST.PRODUCT_ID = PROD.PRODUCT_ID WHERE PROD.PRODUCT_ID=?";
	
	public static final String CUSTOMER_UPDATE_BYID = "UPDATE SPCUSTOMER SET NAME=?,PRODUCT_ID=?,EMAIL=? WHERE CUSTOMER_ID = ?";
	
	public static final String CUSTOMER_DELETE_BYID = "DELETE FROM SPCUSTOMER WHERE CUSTOMER_ID = ?";
	
	public static final String REVENUE_INSERT = "INSERT INTO SPCUSTOMERREVENUE (REVENUE_ID,MONTH,YEAR,CUSTOMER_ID,AMOUNT,ROWCREATIONDATE,ROWMODIFIEDDATE ) Values (SPCUSTOMERREVENUE_S.NEXTVAL,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String REVENUE_DELETE_BY_CUSTID_MONTH_YEAR = "DELETE FROM SPCUSTOMERREVENUE WHERE CUSTOMER_ID=? AND MONTH=? AND YEAR=?";
	
	public static final String REVENUE_GET_BYCUSTID = "SELECT CUSTOMER_ID,MONTH,YEAR,AMOUNT FROM SPCUSTOMERREVENUE WHERE CUSTOMER_ID=?";
	
	public static final String PRODUCT_REV_REPT_UPDATE_BYID = "MERGE INTO SPPRODUCT PROD USING "
			+ "(SELECT PRODUCT_ID,REVENUE,REPUTATION FROM SPPRODUCT WHERE PRODUCT_ID=?) TMP "
			+ "ON (PROD.PRODUCT_ID = TMP.PRODUCT_ID) WHEN MATCHED THEN UPDATE SET "
			+ "PROD.REVENUE=TMP.REVENUE+?,PROD.REPUTATION = TMP.REPUTATION+?,PROD.ROWMODIFIEDDATE = CURRENT_TIMESTAMP";
	
	public static final String CUSTOMER_REV_REPT_UPDATE_BYID = "MERGE INTO SPCUSTOMER CUS USING "
			+ "(SELECT CUSTOMER_ID,REVENUE,REPUTATION FROM SPCUSTOMER WHERE CUSTOMER_ID=?) TMP "
			+ "ON (CUS.CUSTOMER_ID = TMP.CUSTOMER_ID) WHEN MATCHED THEN UPDATE SET "
			+ "CUS.REVENUE=TMP.REVENUE+?,CUS.REPUTATION = TMP.REPUTATION+?,CUS.ROWMODIFIEDDATE = CURRENT_TIMESTAMP";
	
	public static final String REVENUE_GET_BYPRODID = "SELECT REV.CUSTOMER_ID,REV.MONTH,REV.YEAR,REV.AMOUNT "
			+ "FROM SPPRODUCT PROD INNER JOIN SPCUSTOMER CUST "
			+ "ON PROD.PRODUCT_ID = CUST.PRODUCT_ID "
			+ "INNER JOIN SPCUSTOMERREVENUE REV ON CUST.CUSTOMER_ID=REV.CUSTOMER_ID WHERE PROD.PRODUCT_ID=?";
	
}
