package com.bits.saas.util.query;

public final class DBQueries {
	
	public static final String ENTERPRISE_INSERT = "INSERT INTO SPENTERPRISE (ENTERPRISE_ID,NAME) VALUES (SPENTERPRISE_S.NEXTVAL,?)";
	
	public static final String ENTERPRISE_SELECT_BYID = "SELECT ENTERPRISE_ID, NAME FROM SPENTERPRISE WHERE ENTERPRISE_ID=?";
	
	public static final String ENTERPRISE_UPDATE_BYID = "UPDATE SPENTERPRISE SET NAME = ?, ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE ENTERPRISE_ID=?";
	
	public static final String ENTERPRISE_DELETE_BYID = "DELETE FROM SPENTERPRISE WHERE ENTERPRISE_ID = ?";
	
	public static final String ENTERPRISE_SELECT_ALL = "SELECT ENTERPRISE_ID, NAME FROM SPENTERPRISE ORDER BY ENTERPRISE_ID";
	
	public static final String PRODUCT_INSERT = "INSERT INTO SPPRODUCT (PRODUCT_ID,NAME,ENTERPRISE_ID) VALUES (?,?,?)";
	
	public static final String PRODUCT_SELECT_BYID = "SELECT P.PRODUCT_ID,P.NAME,P.REVENUE,P.REPUTATION,P.ENTERPRISE_ID,E.NAME FROM SPPRODUCT P INNER JOIN SPENTERPRISE E ON P.ENTERPRISE_ID = E.ENTERPRISE_ID WHERE P.PRODUCT_ID=?";
	
	public static final String PRODUCT_UPDATE_BYID = "UPDATE SPPRODUCT SET NAME=?,ENTERPRISE_ID=?,ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE PRODUCT_ID=?";
	
	public static final String PRODUCT_SELECT_BYENTID = "SELECT P.PRODUCT_ID,P.NAME,P.REVENUE,P.REPUTATION,P.ENTERPRISE_ID,E.NAME FROM SPPRODUCT P INNER JOIN SPENTERPRISE E ON P.ENTERPRISE_ID = E.ENTERPRISE_ID WHERE P.ENTERPRISE_ID=? ORDER BY P.PRODUCT_ID";
	
	public static final String PRODUCT_DELETE_BYID = "DELETE FROM SPPRODUCT WHERE PRODUCT_ID = ?";
	
	public static final String PRODUCT_GET_SEQ = "SELECT SPPRODUCT_S.NEXTVAL FROM DUAL";
	
	public static final String PRODUCT_DETAIL_INSERT = "INSERT INTO SPPRODUCTDETAIL (PRODUCTDETAIL_ID,PRODUCT_ID,BLOCK1,BLOCK2,BLOCK3) VALUES (SPPRODUCTDETAIL_S.NEXTVAL,?,?,?,?)";
	
	public static final String PRODUCTDETAIL_DELETE_BYPRODID = "DELETE FROM SPPRODUCTDETAIL WHERE PRODUCT_ID = ?";
	
	public static final String PRODUCTDETAIL_SELECT_BYPRODID = "SELECT PRODDET.PRODUCT_ID,PROD.NAME,PRODDET.BLOCK1,PRODDET.BLOCK2,PRODDET.BLOCK3 FROM SPPRODUCTDETAIL PRODDET INNER JOIN SPPRODUCT PROD ON PROD.PRODUCT_ID = PRODDET.PRODUCT_ID WHERE PRODDET.PRODUCT_ID=?";
	
	public static final String PRODUCTDETAIL_UPDATE_BYPRODID = "UPDATE SPPRODUCTDETAIL SET BLOCK1=?,BLOCK2=?,BLOCK3=? WHERE PRODUCT_ID=?";
	
	public static final String CUSTOMER_INSERT = "INSERT INTO SPCUSTOMER(CUSTOMER_ID,NAME,PRODUCT_ID,EMAIL,REPUTATION,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (SPCUSTOMER_S.NEXTVAL,?,?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String CUSTOMER_SELECT_BYID = "SELECT CUST.CUSTOMER_ID,CUST.NAME,CUST.EMAIL,CUST.REPUTATION,CUST.REVENUE,PROD.PRODUCT_ID,PROD.NAME,PROD.REPUTATION,PROD.REVENUE FROM SPCUSTOMER CUST INNER JOIN SPPRODUCT PROD ON CUST.PRODUCT_ID = PROD.PRODUCT_ID WHERE CUST.CUSTOMER_ID=?";
	
	public static final String CUSTOMER_SELECT_BYPRODUCTID = "SELECT CUST.CUSTOMER_ID,CUST.NAME,CUST.EMAIL,CUST.REPUTATION,CUST.REVENUE,PROD.PRODUCT_ID,PROD.NAME,PROD.REPUTATION,PROD.REVENUE FROM SPCUSTOMER CUST INNER JOIN SPPRODUCT PROD ON CUST.PRODUCT_ID = PROD.PRODUCT_ID WHERE PROD.PRODUCT_ID=?";
	
	public static final String CUSTOMER_UPDATE_BYID = "UPDATE SPCUSTOMER SET NAME=?,PRODUCT_ID=?,EMAIL=? WHERE CUSTOMER_ID = ?";
	
	public static final String CUSTOMER_DELETE_BYID = "DELETE FROM SPCUSTOMER WHERE CUSTOMER_ID = ?";
	
	public static final String REVENUE_INSERT = "INSERT INTO SPCUSTOMERREVENUE (REVENUE_ID,MONTH,YEAR,CUSTOMER_ID,AMOUNT,ROWCREATIONDATE,ROWMODIFIEDDATE ) Values (SPCUSTOMERREVENUE_S.NEXTVAL,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String REVENUE_DELETE_BY_CUSTID_MONTH_YEAR = "DELETE FROM SPCUSTOMERREVENUE WHERE CUSTOMER_ID=? AND MONTH=? AND YEAR=?";
	
	public static final String REVENUE_SELECT_BY_CUSTID_MONTH_YEAR = "SELECT AMOUNT FROM SPCUSTOMERREVENUE WHERE CUSTOMER_ID=? AND MONTH=? AND YEAR=?";
	
	public static final String REVENUE_SELECT_BYCUSTID = "SELECT CUSTOMER_ID,MONTH,YEAR,AMOUNT FROM SPCUSTOMERREVENUE WHERE CUSTOMER_ID=? ORDER BY YEAR,MONTH";
	
	public static final String PRODUCT_REV_REPT_UPDATE_BYID = "MERGE INTO SPPRODUCT PROD USING "
			+ "(SELECT PRODUCT_ID,REVENUE,REPUTATION FROM SPPRODUCT WHERE PRODUCT_ID=?) TMP "
			+ "ON (PROD.PRODUCT_ID = TMP.PRODUCT_ID) WHEN MATCHED THEN UPDATE SET "
			+ "PROD.REVENUE=TMP.REVENUE+?,PROD.REPUTATION = TMP.REPUTATION+?,PROD.ROWMODIFIEDDATE = CURRENT_TIMESTAMP";
	
	public static final String CUSTOMER_REV_REPT_UPDATE_BYID = "MERGE INTO SPCUSTOMER CUS USING "
			+ "(SELECT CUSTOMER_ID,REVENUE,REPUTATION FROM SPCUSTOMER WHERE CUSTOMER_ID=?) TMP "
			+ "ON (CUS.CUSTOMER_ID = TMP.CUSTOMER_ID) WHEN MATCHED THEN UPDATE SET "
			+ "CUS.REVENUE=TMP.REVENUE+?,CUS.REPUTATION = TMP.REPUTATION+?,CUS.ROWMODIFIEDDATE = CURRENT_TIMESTAMP";
	
	public static final String REVENUE_SELECT_BYPRODID = "SELECT REV.CUSTOMER_ID,REV.MONTH,REV.YEAR,REV.AMOUNT "
			+ "FROM SPPRODUCT PROD INNER JOIN SPCUSTOMER CUST "
			+ "ON PROD.PRODUCT_ID = CUST.PRODUCT_ID "
			+ "INNER JOIN SPCUSTOMERREVENUE REV ON CUST.CUSTOMER_ID=REV.CUSTOMER_ID WHERE PROD.PRODUCT_ID=? ORDER BY REV.YEAR,REV.MONTH";
	
	public static final String FEATUREREQUEST_GET_SEQ = "SELECT SPFEATUREREQUEST_S.NEXTVAL FROM DUAL";
	
	public static final String FEATUREREQUEST_INSERT = "INSERT INTO SPFEATUREREQUEST (REQUEST_ID,SUBJECT,DESCRIPTION,IMPACT_FACTOR,CUSTOMER_ID,UPVOTE,ISFREEZED,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (?,?,?,?,?,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String FEATUREREQUEST_SELECT_BYID = "SELECT REQ.REQUEST_ID,REQ.SUBJECT,REQ.DESCRIPTION,REQ.IMPACT_FACTOR,REQ.UPVOTE,"
			+ "REQ.ROWCREATIONDATE,REQ.ISFREEZED,REQ.CUSTOMER_ID,CUST.NAME,CUST.REPUTATION,PROD.PRODUCT_ID,PROD.NAME,PROD.REPUTATION FROM SPFEATUREREQUEST REQ "
			+ "INNER JOIN SPCUSTOMER CUST ON REQ.CUSTOMER_ID=CUST.CUSTOMER_ID "
			+ "INNER JOIN SPPRODUCT PROD ON PROD.PRODUCT_ID = CUST.PRODUCT_ID "
			+ "WHERE REQ.REQUEST_ID=?";
	
	public static final String FEATUREREQUEST_SELECT_BYCUSTID = "SELECT REQ.REQUEST_ID,REQ.SUBJECT,REQ.DESCRIPTION,REQ.IMPACT_FACTOR,REQ.UPVOTE,"
			+ "REQ.ROWCREATIONDATE,REQ.ISFREEZED,REQ.CUSTOMER_ID,CUST.NAME,CUST.REPUTATION,PROD.PRODUCT_ID,PROD.NAME,PROD.REPUTATION FROM SPFEATUREREQUEST REQ "
			+ "INNER JOIN SPCUSTOMER CUST ON REQ.CUSTOMER_ID=CUST.CUSTOMER_ID "
			+ "INNER JOIN SPPRODUCT PROD ON PROD.PRODUCT_ID = CUST.PRODUCT_ID "
			+ "WHERE REQ.CUSTOMER_ID=? ORDER BY REQ.IMPACT_FACTOR DESC";
	
	public static final String FEATUREREQUEST_SELECT_BYPRODID = "SELECT REQ.REQUEST_ID,REQ.SUBJECT,REQ.DESCRIPTION,REQ.IMPACT_FACTOR,REQ.UPVOTE,"
			+ "REQ.ROWCREATIONDATE,REQ.ISFREEZED,REQ.CUSTOMER_ID,CUST.NAME,CUST.REPUTATION,PROD.PRODUCT_ID,PROD.NAME,PROD.REPUTATION FROM SPFEATUREREQUEST REQ "
			+ "INNER JOIN SPCUSTOMER CUST ON REQ.CUSTOMER_ID=CUST.CUSTOMER_ID "
			+ "INNER JOIN SPPRODUCT PROD ON PROD.PRODUCT_ID = CUST.PRODUCT_ID "
			+ "WHERE PROD.PRODUCT_ID=? ORDER BY REQ.IMPACT_FACTOR DESC";
	
	public static final String FEATUREREQUEST_UPDATE_BYID = "UPDATE SPFEATUREREQUEST SET SUBJECT=?,DESCRIPTION=?,ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE CUSTOMER_ID=? AND REQUEST_ID=?";
	
	public static final String FEATUREREQUEST_UPDATE_FREEZE_BYID = "UPDATE SPFEATUREREQUEST SET ISFREEZED=1 WHERE REQUEST_ID=?";
	
	public static final String FEATUREREQUEST_UPDATE_UPVOTE_IMPACT_BYID = "MERGE INTO SPFEATUREREQUEST REQ USING "
			+ "(SELECT REQUEST_ID,IMPACT_FACTOR,UPVOTE FROM SPFEATUREREQUEST WHERE REQUEST_ID=?) TMP "
			+ "ON (REQ.REQUEST_ID = TMP.REQUEST_ID) WHEN MATCHED THEN "
			+ "UPDATE SET REQ.IMPACT_FACTOR=TMP.IMPACT_FACTOR+?,REQ.UPVOTE = TMP.UPVOTE+?,REQ.ROWMODIFIEDDATE = CURRENT_TIMESTAMP";
	
	public static final String FEATUREREQUEST_RECALCULATE_IMPORT_FACTORS = "CALL RECALCULATE_IMPACT_FACTOR(?)";
	
	public static final String FEATURE_REQUEST_DETAIL_INSERT = "INSERT INTO SPFEATUREREQVOTEDETAIL (REQUEST_ID,CUSTOMER_ID,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String WORKAROUND_GET_SEQ = "SELECT SPWORKAROUND_S.NEXTVAL FROM DUAL";
	
	public static final String WORKAROUND_INSERT = "INSERT INTO SPWORKAROUND (WORKAROUND_ID,DESCRIPTION,CUSTOMER_ID,REQUEST_ID,UPVOTE,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (?,?,?,?,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String WORKAROUND_UPDATE_BYID = "UPDATE SPWORKAROUND SET DESCRIPTION=?,ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE WORKAROUND_ID=? AND CUSTOMER_ID=?";
	
	public static final String WORKAROUND_SELECT_BYID = "SELECT WA.WORKAROUND_ID,WA.DESCRIPTION,WA.CUSTOMER_ID,WA.REQUEST_ID,"
			+ "WA.UPVOTE,WA.ROWCREATIONDATE,WA.ROWMODIFIEDDATE,REQ.ISFREEZED,REQ.SUBJECT,CUS.NAME FROM "
			+ "SPWORKAROUND WA INNER JOIN SPFEATUREREQUEST REQ ON REQ.REQUEST_ID = WA.REQUEST_ID "
			+ "INNER JOIN SPCUSTOMER CUS ON WA.CUSTOMER_ID = CUS.CUSTOMER_ID "
			+ "WHERE WA.WORKAROUND_ID=? ORDER BY WA.UPVOTE DESC";
	
	public static final String WORKAROUND_SELECT_BYREQID = "SELECT WA.WORKAROUND_ID,WA.DESCRIPTION,WA.CUSTOMER_ID,WA.REQUEST_ID,"
			+ "WA.UPVOTE,WA.ROWCREATIONDATE,WA.ROWMODIFIEDDATE,REQ.ISFREEZED,REQ.SUBJECT,CUS.NAME FROM "
			+ "SPWORKAROUND WA INNER JOIN SPFEATUREREQUEST REQ ON REQ.REQUEST_ID = WA.REQUEST_ID "
			+ "INNER JOIN SPCUSTOMER CUS ON WA.CUSTOMER_ID = CUS.CUSTOMER_ID "
			+ "WHERE WA.REQUEST_ID=? ORDER BY WA.UPVOTE DESC";
	
	public static final String WORKAROUND_DETAIL_INSERT = "INSERT INTO SPWORKAROUNDVOTEDETAIL (WORKAROUND_ID,CUSTOMER_ID,ROWCREATIONDATE,ROWMODIFIEDDATE) VALUES (?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	
	public static final String WORKAROUND_UPDATE_UPVOTE_BYID = "UPDATE SPWORKAROUND SET UPVOTE=(SELECT UPVOTE FROM SPWORKAROUND WHERE WORKAROUND_ID=?)+?,ROWMODIFIEDDATE=CURRENT_TIMESTAMP WHERE WORKAROUND_ID=?";
	
}
